//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCitasMedicas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCitasMedicasEntities1 : DbContext
    {
        public dbCitasMedicasEntities1()
            : base("name=dbCitasMedicasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCentroMedico> tblCentroMedicoes { get; set; }
        public virtual DbSet<tblCita> tblCitas { get; set; }
        public virtual DbSet<tblDoctor> tblDoctors { get; set; }
        public virtual DbSet<tblEspecialidad> tblEspecialidads { get; set; }
        public virtual DbSet<tblEstadoCita> tblEstadoCitas { get; set; }
        public virtual DbSet<tblPaciente> tblPacientes { get; set; }
        public virtual DbSet<tblSeguro> tblSeguroes { get; set; }
    }
}
