//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCitasMedicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCita
    {
        public int idCita { get; set; }
        public int idDoctor { get; set; }
        public int idPaciente { get; set; }
        public int idCentroMedico { get; set; }
        public int idEstadoCita { get; set; }
        public System.DateTime fechaCita { get; set; }
        public System.TimeSpan horaCita { get; set; }
    
        public virtual tblCentroMedico tblCentroMedico { get; set; }
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblEstadoCita tblEstadoCita { get; set; }
        public virtual tblPaciente tblPaciente { get; set; }
    }
}
