//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCitasMedicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCentroMedico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCentroMedico()
        {
            this.tblCitas = new HashSet<tblCita>();
        }
    
        public int idCentroMedico { get; set; }
        public string nombreCentro { get; set; }
        public string telefonoCentro { get; set; }
        public string direccionCentro { get; set; }
        public string paginaWebCentro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCita> tblCitas { get; set; }
    }
}
