//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCitasMedicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDoctor()
        {
            this.tblCitas = new HashSet<tblCita>();
        }
    
        public int idDoctor { get; set; }
        public int idEspecialidad { get; set; }
        public string nombreDoctor { get; set; }
        public string cedulaDoctor { get; set; }
        public Nullable<System.DateTime> fechaNacimientoDoctor { get; set; }
        public string correoDoctor { get; set; }
        public string telefonoDoctor { get; set; }
        public string direccionDoctor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCita> tblCitas { get; set; }
        public virtual tblEspecialidad tblEspecialidad { get; set; }
    }
}
